artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/877826581369082788/cf235aab30a34a57b195c4b0407c9397/artifacts
end_time: null
entry_point_name: ''
experiment_id: '877826581369082788'
lifecycle_stage: active
run_id: cf235aab30a34a57b195c4b0407c9397
run_name: placid-sheep-798
run_uuid: cf235aab30a34a57b195c4b0407c9397
source_name: ''
source_type: 4
source_version: ''
start_time: 1751394380163
status: 1
tags: []
user_id: reema
