artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/877826581369082788
creation_time: 1751394308699
experiment_id: '877826581369082788'
last_update_time: 1751394308699
lifecycle_stage: active
name: jgkhj
