artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/195348868263663897/e8017eddc99043ea888f680bd19c5310/artifacts
end_time: 1751839308080
entry_point_name: ''
experiment_id: '195348868263663897'
lifecycle_stage: active
run_id: e8017eddc99043ea888f680bd19c5310
run_name: glamorous-sheep-419
run_uuid: e8017eddc99043ea888f680bd19c5310
source_name: ''
source_type: 4
source_version: ''
start_time: 1751839165795
status: 4
tags: []
user_id: reema
