artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/766495689488191200
creation_time: 1751899957667
experiment_id: '766495689488191200'
last_update_time: 1751899957667
lifecycle_stage: active
name: trying_out
