artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/284368853934598340
creation_time: 1751839339730
experiment_id: '284368853934598340'
last_update_time: 1751839339730
lifecycle_stage: active
name: cdsf
