artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/302402584674284791/7ac1d4295ded4c49a38d72c790bdcec7/artifacts
end_time: 1751395582834
entry_point_name: ''
experiment_id: '302402584674284791'
lifecycle_stage: active
run_id: 7ac1d4295ded4c49a38d72c790bdcec7
run_name: glamorous-loon-317
run_uuid: 7ac1d4295ded4c49a38d72c790bdcec7
source_name: ''
source_type: 4
source_version: ''
start_time: 1751395582778
status: 4
tags: []
user_id: reema
