artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/850468030315623037
creation_time: 1751840762362
experiment_id: '850468030315623037'
last_update_time: 1751840762362
lifecycle_stage: active
name: dsf
