artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/533464386382950604
creation_time: 1752223373333
experiment_id: '533464386382950604'
last_update_time: 1752223373333
lifecycle_stage: active
name: Wine_Evaluation
