artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/766495689488191200/3fb7bc6ad9da4f0fa9d19c577b9ba55d/artifacts
end_time: 1751900447393
entry_point_name: ''
experiment_id: '766495689488191200'
lifecycle_stage: active
run_id: 3fb7bc6ad9da4f0fa9d19c577b9ba55d
run_name: powerful-robin-826
run_uuid: 3fb7bc6ad9da4f0fa9d19c577b9ba55d
source_name: ''
source_type: 4
source_version: ''
start_time: 1751899959369
status: 3
tags: []
user_id: reema
