artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/331551930699560967/a2e85cf6fd69431faf6f28aa0c620b8a/artifacts
end_time: 1752225639840
entry_point_name: ''
experiment_id: '331551930699560967'
lifecycle_stage: active
run_id: a2e85cf6fd69431faf6f28aa0c620b8a
run_name: unleashed-trout-554
run_uuid: a2e85cf6fd69431faf6f28aa0c620b8a
source_name: ''
source_type: 4
source_version: ''
start_time: 1752225587549
status: 4
tags: []
user_id: reema
