artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651
creation_time: 1751797297753
experiment_id: '734487550268932651'
last_update_time: 1751797297753
lifecycle_stage: active
name: dsfsdf
