artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/594801963139786423
creation_time: 1751837887571
experiment_id: '594801963139786423'
last_update_time: 1751837887571
lifecycle_stage: active
name: wdsdf
