artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/284368853934598340/e51c1e1c0d734273a36281581cf1bf4f/artifacts
end_time: 1751839386725
entry_point_name: ''
experiment_id: '284368853934598340'
lifecycle_stage: active
run_id: e51c1e1c0d734273a36281581cf1bf4f
run_name: industrious-bat-404
run_uuid: e51c1e1c0d734273a36281581cf1bf4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1751839341420
status: 4
tags: []
user_id: reema
