artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/877826581369082788/a3b11e3299d643df8cd0cb9796a2f820/artifacts
end_time: 1751394314139
entry_point_name: ''
experiment_id: '877826581369082788'
lifecycle_stage: active
run_id: a3b11e3299d643df8cd0cb9796a2f820
run_name: placid-deer-90
run_uuid: a3b11e3299d643df8cd0cb9796a2f820
source_name: ''
source_type: 4
source_version: ''
start_time: 1751394310555
status: 4
tags: []
user_id: reema
