artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/302402584674284791
creation_time: 1751395548460
experiment_id: '302402584674284791'
last_update_time: 1751395548460
lifecycle_stage: active
name: fdsg
