artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/302402584674284791/5898a1b52be04da5a130420ea0203ff1/artifacts
end_time: 1751395652941
entry_point_name: ''
experiment_id: '302402584674284791'
lifecycle_stage: active
run_id: 5898a1b52be04da5a130420ea0203ff1
run_name: auspicious-wren-770
run_uuid: 5898a1b52be04da5a130420ea0203ff1
source_name: ''
source_type: 4
source_version: ''
start_time: 1751395652883
status: 4
tags: []
user_id: reema
