artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/331551930699560967
creation_time: 1752225584813
experiment_id: '331551930699560967'
last_update_time: 1752225584813
lifecycle_stage: active
name: Iris_Evaluation
