artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651/d6c58cef84cd45a0af07205b4f53ac18/artifacts
end_time: 1751799004758
entry_point_name: ''
experiment_id: '734487550268932651'
lifecycle_stage: active
run_id: d6c58cef84cd45a0af07205b4f53ac18
run_name: nimble-donkey-378
run_uuid: d6c58cef84cd45a0af07205b4f53ac18
source_name: ''
source_type: 4
source_version: ''
start_time: 1751798992397
status: 4
tags: []
user_id: reema
