artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/870776825165380488
creation_time: 1751841048889
experiment_id: '870776825165380488'
last_update_time: 1751841048889
lifecycle_stage: active
name: dsv
