artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651/a0d70d5b103c4bb78da36c5190bd51d5/artifacts
end_time: 1751798020159
entry_point_name: ''
experiment_id: '734487550268932651'
lifecycle_stage: active
run_id: a0d70d5b103c4bb78da36c5190bd51d5
run_name: respected-kite-632
run_uuid: a0d70d5b103c4bb78da36c5190bd51d5
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797947795
status: 4
tags: []
user_id: reema
