artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/331551930699560967/a3e1931788a64598b6efaa51e15d8ba9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '331551930699560967'
lifecycle_stage: active
run_id: a3e1931788a64598b6efaa51e15d8ba9
run_name: brawny-stork-623
run_uuid: a3e1931788a64598b6efaa51e15d8ba9
source_name: ''
source_type: 4
source_version: ''
start_time: 1752225811494
status: 1
tags: []
user_id: reema
