artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651/9c8e3330675c4d61aabe8eeed4ae4364/artifacts
end_time: 1751798268387
entry_point_name: ''
experiment_id: '734487550268932651'
lifecycle_stage: active
run_id: 9c8e3330675c4d61aabe8eeed4ae4364
run_name: merciful-shad-24
run_uuid: 9c8e3330675c4d61aabe8eeed4ae4364
source_name: ''
source_type: 4
source_version: ''
start_time: 1751798225703
status: 4
tags: []
user_id: reema
