artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/687018567240761173
creation_time: 1751831049991
experiment_id: '687018567240761173'
last_update_time: 1751831049991
lifecycle_stage: active
name: dcggfsjh
