artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/687018567240761173/2625be35b15747e28ddebf6c20b9a3c8/artifacts
end_time: 1751831066543
entry_point_name: ''
experiment_id: '687018567240761173'
lifecycle_stage: active
run_id: 2625be35b15747e28ddebf6c20b9a3c8
run_name: entertaining-koi-941
run_uuid: 2625be35b15747e28ddebf6c20b9a3c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1751831052960
status: 4
tags: []
user_id: reema
