artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/195348868263663897
creation_time: 1751837892925
experiment_id: '195348868263663897'
last_update_time: 1751837892925
lifecycle_stage: active
name: csdv#
