artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/470904293318649845
creation_time: 1752223120893
experiment_id: '470904293318649845'
last_update_time: 1752223120893
lifecycle_stage: active
name: Wine_WorkFlow_Evaluation
