artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651/7bd00132c8b34b0bb8a9019fd2aa3279/artifacts
end_time: 1751800173971
entry_point_name: ''
experiment_id: '734487550268932651'
lifecycle_stage: active
run_id: 7bd00132c8b34b0bb8a9019fd2aa3279
run_name: charming-roo-779
run_uuid: 7bd00132c8b34b0bb8a9019fd2aa3279
source_name: ''
source_type: 4
source_version: ''
start_time: 1751799360663
status: 4
tags: []
user_id: reema
