artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651/7962a07708cc4c13bc6a827fadd6666a/artifacts
end_time: 1751797653718
entry_point_name: ''
experiment_id: '734487550268932651'
lifecycle_stage: active
run_id: 7962a07708cc4c13bc6a827fadd6666a
run_name: bustling-loon-287
run_uuid: 7962a07708cc4c13bc6a827fadd6666a
source_name: ''
source_type: 4
source_version: ''
start_time: 1751797647230
status: 4
tags: []
user_id: reema
