artifact_uri: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/734487550268932651/bd3ef047d92a4da1aa934da0618905cf/artifacts
end_time: 1751798446101
entry_point_name: ''
experiment_id: '734487550268932651'
lifecycle_stage: active
run_id: bd3ef047d92a4da1aa934da0618905cf
run_name: persistent-crab-671
run_uuid: bd3ef047d92a4da1aa934da0618905cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1751798394735
status: 4
tags: []
user_id: reema
