artifact_location: file:///C:/Users/reema/OneDrive/Dokumente/evaluation/Framework_Evaluation/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/720044898551446016
creation_time: 1751841123606
experiment_id: '720044898551446016'
last_update_time: 1751841123606
lifecycle_stage: active
name: dfscfs
